version: 2

updates:

  # Production dependencies
  - package-ecosystem: "uv"
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: "weekly"
    labels:
      - "production"
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore (production deps)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      boto:
        patterns:
          - "boto*"

  # Development dependencies
  - package-ecosystem: "uv"
    directory: "/"
    allow:
      - dependency-type: "development"
    schedule:
      interval: "weekly"
    labels:
      - "development"
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore (development deps)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      development:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
    commit-message:
      prefix: "chore (gha)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      all_gha:
        patterns:
          - "*"

  # Docker images
  - package-ecosystem: "docker"
    directory: "/tests"
    schedule:
      interval: "monthly"
    labels:
      - "docker"
    commit-message:
      prefix: "chore (docker)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns:
          - "*"
