version: 2

updates:

  # Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore (dependencies)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      development:
        dependency-type: "development"
      boto:
        patterns:
          - "boto*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
    commit-message:
      prefix: "chore (gha)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      all_gha:
        patterns:
          - "*"

  # Docker images
  - package-ecosystem: "docker-compose"
    directory: "/tests"
    schedule:
      interval: "monthly"
    labels:
      - "docker"
    commit-message:
      prefix: "chore (docker)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns:
          - "*"
