version: 2
updates:

  - package-ecosystem: "uv"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/tests"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
    assignees:
      - "brunns"
    cooldown:
      default-days: 7
